global:
  smtp_from: 'example@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'gannochenko.dev@gmail.com'
  smtp_auth_identity: 'gannochenko.dev@gmail.com'
  smtp_auth_password: 'dvcxxsilayxqwpqk'

route:
  receiver: admin

receivers:
  - name: admin
    email_configs:
      - to: 'gannochenko.dev@gmail.com'
