route:
  receiver: admin

receivers:
  - name: admin
    email_configs:
      - to: 'gannochenko.dev@gmail.com'
        from: 'example@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'gannochenko.dev@gmail.com'
        auth_identity: 'gannochenko.dev@gmail.com'
        auth_password: 'dvcxxsilayxqwpqk'