global:
  smtp_from: 'example@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'gannochenko.dev@gmail.com'
  smtp_auth_identity: 'gannochenko.dev@gmail.com'
  smtp_auth_password: 'dvcxxsilayxqwpqk'

route:
  receiver: admin
  routes:
    - match:
        app_type: go
      # fallback receiver
      receiver: go-admin
      routes:
        - match:
            severity: critical
          receiver: go-manager
        - match:
            severity: warning
          receiver: go-teamlead

receivers:
  - name: admin
    email_configs:
      - to: 'gannochenko.dev@gmail.com'
  - name: go-admin
    email_configs:
      - to: 'gannochenko.sv@gmail.com'
  - name: go-manager
    email_configs:
      - to: 'gannochenko.sv@gmail.com'
#  - name: go-manager
#    slack_configs:
#      - channel: '#prometheus'
#        api_url: 'webhook url here'
#        title: 'Message title'
#        text: 'Message text'
  - name: go-teamlead
    email_configs:
      - to: 'gannochenko.teamlead@gmail.com'
