groups:
  - name: my-rules
    rules:
      - record: job:go_app_response_latency:5m
        expr: rate(go_app_response_latency_sum[5m]) / rate(go_app_response_latency_count[5m])
      - alert: GoAppDown
        expr: up{job="prom_go_app"} == 0